const razones = [
    "Tu sonrisa ilumina mi día",
    "Me haces reír incluso en los momentos más difíciles",
    "Entiendes mis sentimientos sin que tenga que decir una palabra",
    "Tus ojos brillan cuando estás feliz y eso me llena el alma",
    "Admiro tu dedicación y la pasión con la que haces todo",
    "Me haces sentir especial cada día",
    "Siempre me apoyas en todos mis sueños",
    "Tu inteligencia me inspira a crecer como persona",
    "Tu dulzura y amabilidad con todos me conmueve",
    "Me haces sentir en casa solo con estar contigo",
    "Eres valiente y fuerte ante cualquier desafío",
    "Me entiendes mejor que nadie en el mundo",
    "Haces que cada momento juntos sea único y especial",
    "Sacas lo mejor de mí, me haces querer ser mejor persona",
    "Tu amor es incondicional, puro y sincero",
    "Me haces sentir la persona más feliz del mundo",
    "Tu pelo es hermoso y suave, me encanta acariciarlo",
    "Amo tu forma de ser, auténtica y única",
    "Tu sonrisa me llena de vida",
    "Tus abrazos me hacen sentir protegido y amado",
    "Cuando me mirás, siento que todo está bien",
    "Eres mi paz en medio del caos",
    "Amo cómo te ríes, me contagias alegría",
    "Me haces sentir amado sin necesidad de palabras",
    "Tu ternura es una de las cosas más bellas que existen",
    "Siempre sabes qué decir para hacerme sentir mejor",
    "Amo pasar tiempo contigo, aunque no hagamos nada",
    "Tus besos tienen el poder de detener el tiempo",
    "Eres mi persona favorita en todo el universo",
    "Me haces sentir afortunado todos los días",
    "Eres mi compañera perfecta en esta vida",
    "Amo cómo me tomas la mano y no la sueltas",
    "Contigo me siento completo",
    "Amo cómo me miras cuando piensas que no me doy cuenta",
    "Tu risa es mi sonido favorito",
    "Eres la razón por la que sonrío todos los días",
    "Tus ocurrencias me divierten y me hacen amarte más",
    "Siempre estás ahí cuando más te necesito",
    "Amo cómo me haces sentir importante",
    "Tus ojitos marrones me hipnotizan",
    "Amo cómo te emocionas con cosas pequeñas",
    "Eres mi lugar seguro",
    "Cada día contigo es una bendición",
    "Me haces sentir amado con cada gesto",
    "Tu voz me calma y me enamora",
    "Me encanta ver películas abrazados contigo",
    "Me encanta planear el futuro contigo",
    "Amo cómo me haces reír sin esfuerzo",
    "Me haces creer en el amor verdadero",
    "Cada abrazo tuyo es un refugio",
    "Amo cómo te preocupas por los demás",
    "Tus detalles me demuestran cuánto me amas",
    "Me haces sentir que todo es posible",
    "Tu amor me da fuerzas para seguir adelante",
    "Me haces ver la belleza en la vida",
    "Tu forma de cuidarme es única",
    "Amo cómo compartimos sueños y metas",
    "Admiro tu sensibilidad y tu corazón enorme",
    "Eres todo lo que siempre soñé",
    "Amo despertarme a tu lado",
    "Eres mi mejor amiga y mi amor a la vez",
    "Amo cómo nos entendemos sin hablar",
    "Tu compañía me hace feliz en cualquier lugar",
    "Tu energía me llena de vida",
    "Tus palabras me abrazan el alma",
    "Amo cómo me escuchas con atención",
    "Me haces sentir libre y amado al mismo tiempo",
    "Me inspiras a ser mi mejor versión",
    "Amo cómo celebras mis logros conmigo",
    "Tus defectos también te hacen perfecta para mí",
    "Adoro nuestras conversaciones profundas",
    "Eres mi hogar, sin importar dónde estemos",
    "Me haces sentir orgulloso de ser tu pareja",
    "Amo cómo compartes tus pensamientos conmigo",
    "Contigo aprendí lo que es el amor de verdad",
    "Eres la razón por la que creo en nosotros",
    "Me haces sentir amado tal como soy",
    "Amo nuestras bromas internas",
    "Tus caricias me llenan el corazón",
    "Amo cómo haces que todo sea especial",
    "Me encanta cómo hueles",
    "Adoro cómo te ves cuando te ríes de mis tonterías",
    "Amo cómo me haces sentir vivo",
    "Siempre sabes cómo hacerme sonreír",
    "Tu forma de ver el mundo me enseña cada día",
    "Eres un regalo que la vida me dio",
    "Amo cómo te emocionas con los pequeños gestos",
    "Tus abrazos son mi medicina",
    "Amo cuando me llamas con cariño",
    "Cada segundo contigo es un tesoro",
    "Tu belleza me deja sin aliento",
    "Tus ojos me hablan sin palabras",
    "Me haces sentir que soy suficiente",
    "Tu presencia mejora mi día automáticamente",
    "Cada vez que te veo, me vuelvo a enamorar",
    "Eres mi razón para sonreír incluso en los días difíciles",
    "Amo cómo respetas mis tiempos y mis emociones",
    "Eres magia en forma de persona",
    "Porque contigo todo tiene sentido",
    "Porque gracias a ti, soy más feliz"
  ];
  
  export default razones;
  